---
language: python
python:
  - '3.7'
sudo: required
dist: xenial
install:
  - pip install flake8 jsonschema

script:
  - flake8 bin/hack-sound-server.in .
  - jsonschema -i data/metadata.json ci/metadata.schema.json
